### PR TITLE
I added necessary files

### PR DESCRIPTION
**Pull request by Hamas2000**
The Pokémon Search App is a web application designed to provide detailed information about any Pokémon. Users can search for Pokémon by entering their name or ID number. Upon searching, the app fetches data from a Pokémon API and displays a variety of information, including the Pokémon's image, name, ID, weight, height, types, and base stats (HP, Attack, Defense, Special Attack, Special Defense, and Speed).

The application features a clean and intuitive interface, making it easy for users to input search queries and view the results. The responsive design ensures that the app is usable across various devices, from desktop computers to mobile phones.

Key functionalities include:

- **Search Functionality**: Allows users to search for Pokémon by name or ID, providing real-time feedback.
- **Detailed Pokémon Information**: Displays comprehensive information about the Pokémon, including its image, ID, name, weight, height, types, and stats.
- **Error Handling**: Displays an error message if the Pokémon is not found, improving the user experience.
- **Responsive Design**: Ensures the app works well on different screen sizes and devices.

This project is ideal for Pokémon fans and developers looking to learn more about using APIs in web development. It showcases how to create a dynamic, user-friendly interface that interacts with an external API to fetch and display data.

### CODE REVIEW

**Comment by Hamas2000** [comment]
@Orzala-2024 Dearest Lima, Please review my project. here is the screenshots that it passes freecodecamp and also the alert worked but in the project because of the linter error I had to bring changes. 
Capture1
<img width="957" alt="Capture2" src="https://github.com/Hamas2000/Build-a-Pok-mon-Search-

**Comment by Orzala-2024** [comment]
@Hamas2000 ,
Your project is great . 
Good Luck!

**Review by ahzamir — APPROVED** [review]
### Hi @Hamas2000 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Pokemon Search App project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

**Comment by Hamas2000** [comment]
@ahzamir Thanks for the reviewing and approval of my project.

**Pull request merged**
